name: Шаблон для roadmap
description: Шаблоны для задач по описанию Roadmap
title: '[Roadmap] Планирование'
type: Roadmap
projects: ['Phoenix-Games-Revolution/7']
body:
  - type: dropdown
    id: plan
    attributes:
      label: Планирование
      description: Выбери тип плана, который нужно описать
      options:
        - Архитектура
        - Стадии разработки
        - Менеджмент
        - Маркетинг
        - Бизнес
        - Контент
    validations:
      required: true

  - type: textarea
    id: about
    attributes:
      label: О чём задача
      description: Что должно быть описано
      value: |
        Опишите сферу планирования и результат, ожидаемый в ПР