name: Юнит Мезолита
description: Задача на подготовку описания юнита эпохи Мезолита
title: '[Mesolithic Unit] Название юнита'
type: Units
projects: ['Phoenix-Games-Revolution/7']
body:
  - type: dropdown
    id: unit-name
    attributes:
      label: Название юнита
      description: Выбери юнита
      options:
        - Hunter
        - Advanced Gatherer
        - Fisher
        - Firekeeper
        - Shaman
        - Scout
        - Slinger
        - Pack Animal Handler
    validations:
      required: true
