name: Навыки юнита Палеолита
description: Задача на описание навыков юнита эпохи Палеолита
title: '[Paleolithic Unit Skills] Название юнита'
type: Units
projects: ['Phoenix-Games-Revolution/7']
body:
  - type: dropdown
    id: unit-name
    attributes:
      label: Название юнита
      description: Выбери юнита для описания его навыков
      options:
        - Hunter
        - Gatherer
        - Fisher
        - Firekeeper
        - Shaman
        - Scout
        - Slinger
    validations:
      required: true
  - type: dropdown
    id: skill-tree-type
    attributes:
      label: Тип древа навыков
      description: Укажи структуру древа навыков
      options:
        - Только пассивные навыки (passive)
        - Только активные навыки (active)
        - Смешанные навыки (mixed)
    validations:
      required: true
