name: Юнит Энеолита
description: Задача на подготовку описания юнита эпохи Энеолита
title: '[Chalcolithic Unit] Название юнита'
type: Units
projects: ['Phoenix-Games-Revolution/7']
body:
  - type: dropdown
    id: unit_name
    attributes:
      label: Название юнита
      description: Выбери юнита
      options:
        - Spearman
        - Archer
        - Slinger
        - Miner
        - Smith
        - Priest
        - Scout
        - Wagoner
        - Hunter
    validations:
      required: true
