name: Навыки юнита Бронзового века
description: Задача на описание навыков юнита эпохи Бронзового века
title: '[Bronze Age Unit Skills] Название юнита'
type: Units
projects: ['Phoenix-Games-Revolution/7']
body:
  - type: dropdown
    id: unit-name
    attributes:
      label: Название юнита
      description: Выбери юнита для описания его навыков
      options:
        - Bronze Swordsman
        - Archer
        - Chariot Archer
        - Spearman
        - Builder
        - Merchant
        - Priest
        - Scout
        - Siege Engineer
    validations:
      required: true
  - type: dropdown
    id: skill-tree-type
    attributes:
      label: Тип древа навыков
      description: Укажи структуру древа навыков
      options:
        - Только пассивные навыки (passive)
        - Только активные навыки (active)
        - Смешанные навыки (mixed)
    validations:
      required: true
