name: Юнит Раннего Железного века
description: Задача на подготовку описания юнита эпохи Раннего Железного века
title: '[Early Iron Age Unit] Название юнита'
type: Units
projects: ['Phoenix-Games-Revolution/7']
body:
  - type: dropdown
    id: unit_name
    attributes:
      label: Название юнита
      description: Выбери юнита
      options:
        - Iron Swordsman
        - Heavy Spearman
        - Crossbowman
        - War Chariot
        - Siege Ram Operator
        - High Priest
        - Engineer
        - Scout
        - Trader
    validations:
      required: true
